#!/usr/bin/env python3
"""Generate the probe's write allow-list from this tree's NV2A device model.

The allow-list is DERIVED, never transcribed. hw/xbox/nv2a/nv2a.c owns the
block table; this reads it and emits nv2a_window.h. Run with --check in CI to
fail if the header has drifted from the model.

Why generated: a hand-copied address that is one digit wrong is a write into
whatever lives next door, and on this machine "next door" eventually means
flash or the SMC. A transcription cannot be re-verified; a derivation can.
"""
import argparse, os, re, sys

ENTRY = re.compile(
    r"ENTRY\(\s*(\w+)\s*,\s*\w+\s*,\s*(0x[0-9a-fA-F]+)\s*,\s*(0x[0-9a-fA-F]+)\s*\)")
WINDOW = re.compile(
    r'memory_region_init\(\s*&d->mmio\s*,[^,]*,\s*"nv2a-mmio"\s*,\s*(0x[0-9a-fA-F]+)\s*\)')

# Blocks whose writes phase one refuses even though they sit inside the window.
# Each needs a reason; an unexplained exclusion is one somebody deletes later.
PHASE1_WRITE_EXCLUDED = {
    "USER": "FIFO DMA-push user area: a write here submits pushbuffer work, "
            "which phase one explicitly does not do.",
}

# PRAMIN (0x700000, 1 MiB) is real silicon but its ENTRY is commented out in
# nv2a.c, so this tree models nothing there and a measured mask would have no
# counterpart to disagree with. strip_comments() keeps it out of the list
# entirely rather than listing it as unwritable, because "absent from the
# model" and "modelled but refused" are different facts.

def strip_comments(src):
    """Remove C comments before matching.

    Not cosmetic. nv2a.c carries a commented-out block:

        // ENTRY(PRAMIN,   pramin,   0x700000, 0x100000),

    and a regex over raw text happily matches it, which would have put a block
    this tree does not model into the WRITE allow-list. A generator that reads
    disabled code is no safer than the transcription it replaced.
    """
    src = re.sub(r"/\*.*?\*/", " ", src, flags=re.S)
    src = re.sub(r"//[^\n]*", " ", src)
    return src


def parse(nv2a_c):
    src = strip_comments(open(nv2a_c, encoding="utf-8").read())
    m = WINDOW.search(src)
    if not m:
        sys.exit("gen_window: could not find the nv2a-mmio memory_region_init "
                 "in %s -- the model changed shape, so this generator must be "
                 "updated rather than guessed around." % nv2a_c)
    size = int(m.group(1), 16)
    # Only the blocktable initialiser, not every ENTRY-looking macro in the file.
    start = src.index("blocktable[NV_NUM_BLOCKS] = {")
    end = src.index("};", start)
    blocks = [(n, int(o, 16), int(s, 16)) for n, o, s in ENTRY.findall(src[start:end])]
    if not blocks:
        sys.exit("gen_window: blocktable parsed to zero entries")
    for n, o, s in blocks:
        if o + s > size:
            sys.exit("gen_window: block %s (0x%06x+0x%06x) runs past the 0x%x "
                     "window" % (n, o, s, size))
    return size, sorted(blocks, key=lambda b: b[1])

def render(size, blocks, nv2a_c):
    w = [b for b in blocks if b[0] not in PHASE1_WRITE_EXCLUDED]
    out = []
    A = out.append
    A("/* GENERATED by tools/nv2a_probe/gen_window.py -- do not edit.")
    A(" *")
    A(" * Source of truth: %s" % nv2a_c)
    A(" * Regenerate:      python3 tools/nv2a_probe/gen_window.py --write")
    A(" * Verify:          python3 tools/nv2a_probe/gen_window.py --check")
    A(" *")
    A(" * The NV2A MMIO BAR is %d MiB. Everything outside it is refused by the" % (size >> 20))
    A(" * probe itself. Flash is mirrored at 0xff000000 and the SMC, SMBus and")
    A(" * EEPROM are I2C devices behind I/O ports -- none of them is MMIO, so an")
    A(" * MMIO-only probe cannot reach them even if this list were wrong.")
    A(" */")
    A("#ifndef NV2A_WINDOW_H")
    A("#define NV2A_WINDOW_H")
    A("")
    A("#include <stdint.h>")
    A("#include <stdbool.h>")
    A("")
    A("#define NV2A_MMIO_SIZE 0x%08xu" % size)
    A("")
    A("typedef struct { const char *name; uint32_t offset, size; bool writable; } nv2a_block_t;")
    A("")
    A("static const nv2a_block_t kNv2aBlocks[] = {")
    for n, o, s in blocks:
        excl = n in PHASE1_WRITE_EXCLUDED
        A('    { "%s",%s 0x%06xu, 0x%06xu, %s },' %
          (n, " " * max(0, 9 - len(n)), o, s, "false" if excl else "true"))
    A("};")
    A("#define NV2A_NUM_BLOCKS %d" % len(blocks))
    A("")
    for n, why in sorted(PHASE1_WRITE_EXCLUDED.items()):
        A("/* write-excluded: %s -- %s */" % (n, why))
    A("")
    A("/* Reads may be wider than writes: any offset inside the BAR. */")
    A("static inline bool nv2a_offset_readable(uint32_t off)")
    A("{")
    A("    return off + 4u > off && off + 4u <= NV2A_MMIO_SIZE;")
    A("}")
    A("")
    A("/* Writes must land inside a modelled, write-enabled block. */")
    A("static inline bool nv2a_offset_writable(uint32_t off)")
    A("{")
    A("    if (off & 3u) return false;              /* unaligned */")
    A("    if (off + 4u <= off) return false;       /* wrap */")
    A("    for (int i = 0; i < NV2A_NUM_BLOCKS; ++i) {")
    A("        const nv2a_block_t *b = &kNv2aBlocks[i];")
    A("        if (!b->writable) continue;")
    A("        if (off >= b->offset && off + 4u <= (uint32_t)(b->offset + b->size))")
    A("            return true;")
    A("    }")
    A("    return false;")
    A("}")
    A("")
    A("#endif /* NV2A_WINDOW_H */")
    return "\n".join(out) + "\n"

def main():
    p = argparse.ArgumentParser()
    p.add_argument("--root", default=os.path.join(os.path.dirname(__file__), "..", ".."))
    p.add_argument("--write", action="store_true")
    p.add_argument("--check", action="store_true")
    p.add_argument("--print-blocks", action="store_true")
    a = p.parse_args()
    root = os.path.abspath(a.root)
    nv2a_c = os.path.join(root, "hw", "xbox", "nv2a", "nv2a.c")
    rel = os.path.relpath(nv2a_c, root)
    size, blocks = parse(nv2a_c)
    text = render(size, blocks, rel)
    hdr = os.path.join(root, "tools", "nv2a_probe", "probe", "nv2a_window.h")
    if a.print_blocks:
        print("window 0x%08x (%d MiB), %d blocks" % (size, size >> 20, len(blocks)))
        for n, o, s in blocks:
            mark = "" if n not in PHASE1_WRITE_EXCLUDED else "   [writes refused]"
            print("  %-9s 0x%06x .. 0x%06x  (0x%06x)%s" % (n, o, o + s, s, mark))
        return 0
    if a.check:
        if not os.path.exists(hdr):
            print("nv2a_window.h missing; run --write", file=sys.stderr); return 1
        if open(hdr, encoding="utf-8").read() != text:
            print("nv2a_window.h is stale: %s changed. Run "
                  "tools/nv2a_probe/gen_window.py --write" % rel, file=sys.stderr)
            return 1
        print("nv2a_window.h matches %s" % rel); return 0
    if a.write:
        os.makedirs(os.path.dirname(hdr), exist_ok=True)
        open(hdr, "w", encoding="utf-8").write(text)
        print("wrote %s" % os.path.relpath(hdr, root)); return 0
    p.error("one of --write / --check / --print-blocks")

if __name__ == "__main__":
    sys.exit(main())
