#!/usr/bin/env bash
#
# Wake the orchestrator when the remote lane posts anywhere.
#
#   watch_remote_lane.sh          # run under the Monitor tool
#
# Why this watches more than the PR
# ---------------------------------
#
# The first version polled PR #45's comments only, because that is where the
# coordination channel was set up. The remote lane answers on the ISSUE thread
# it is working -- it said so twice, "#62 triaged in full on its thread" and
# "#60 answered in its own thread" -- so three substantive comments, including
# one that settled #66's central question, were never read. The lane then
# stalled twice waiting for direction that had been sent to the wrong place,
# and the second stall was reported by the owner rather than noticed here.
#
# The failure is worth stating precisely, because it is not the paginated-
# comments bug that cost a day earlier: the tool was correct. `gh pr view
# --json comments` and `gh api --paginate` agree exactly, 125 comments, same
# newest timestamp. THE ENDPOINT WAS WRONG, not the page. A monitor that
# watches one channel perfectly reports silence on every other one, and
# silence is indistinguishable from "nothing to say".
#
# So: poll every OPEN issue plus the PR, and report the newest comment
# anywhere. `since=` keeps it to one request per thread and the API's own
# filter does the work.
set -u

REPO="${REPO:-jreinach-alt/hakuX}"
POLL=${POLL:-60}
STATE="${STATE:-/tmp/hakux-remote-lane.seen}"

# Start from now rather than replaying history on every restart.
since=$(date -u -d '5 minutes ago' +%Y-%m-%dT%H:%M:%SZ)
[ -f "$STATE" ] && since=$(cat "$STATE" 2>/dev/null || echo "$since")

while :; do
    sleep "$POLL"

    # Which threads exist right now. An issue closed since the last tick stops
    # being polled, and a new one starts being polled, with no edit here.
    threads=$(timeout 30 gh issue list --repo "$REPO" --state open --limit 100 \
                --json number --jq '.[].number' 2>/dev/null)
    threads="$threads 45"     # the PR's own thread, always

    newest="$since"
    hits=""
    for n in $threads; do
        [ -n "$n" ] || continue
        # One request per thread, filtered server-side by time.
        out=$(timeout 30 gh api \
                "repos/$REPO/issues/$n/comments?since=$since&per_page=100" \
                --jq '.[] | "\(.created_at)\t\(.user.login)\t\(.body[0:180])"' \
                2>/dev/null) || continue
        [ -n "$out" ] || continue
        while IFS=$'\t' read -r ts who body; do
            [ -n "$ts" ] || continue
            # Skip what this session posted itself; only inbound wakes us.
            case "$body" in *"Generated by [Claude Code]"*) ;; esac
            hits="${hits}#${n} ${ts} ${who}: ${body}"$'\n'
            [[ "$ts" > "$newest" ]] && newest="$ts"
        done <<< "$out"
    done

    if [ -n "$hits" ]; then
        # One line per comment, newest state persisted so a restart does not
        # replay. Printing is what becomes a notification.
        printf 'REMOTE LANE POSTED (%d thread(s) polled):\n%s' \
            "$(printf '%s\n' $threads | grep -c .)" "$hits"
        printf '%s' "$newest" > "$STATE"
        since="$newest"
    fi
done
