#!/usr/bin/env python3
"""Carve the ACI migration field list, and the struct it describes, out of the
tree so the harness tests the real thing rather than a copy.

Two outputs, both generated:

  build/carved.c       the three VMStateDescription objects and the
                       MCPXACIState typedef, lifted verbatim from
                       hw/xbox/mcpx/aci.c
  build/members.c.inc  one row per member of `struct AC97LinkState` as it
                       stands in hw/audio/ac97_int.h, with the offset and size
                       computed by the compiler rather than by this script

The second is the drift gate, and it is the reason this is generated instead
of hand-written: a member added to AC97LinkState later shows up here with no
classification in the harness, and the harness fails until someone decides
whether it is guest state or not. A hand-written list would just stay silent,
which is the exact failure mode issue #75 is about -- state that is not
migrated and says nothing.
"""
import argparse
import os
import re
import sys


def read(path):
    with open(path) as fh:
        return fh.read()


def extract_block(src, start_re, what, semicolon=True):
    """Return the text from the match of start_re through its balanced closing
    brace, plus the trailing semicolon for a declaration (not for a function
    body, where the next semicolon is inside whatever follows -- which is how
    this first went wrong)."""
    m = re.search(start_re, src)
    if not m:
        sys.exit("carve.py: could not find %s (pattern %r)" % (what, start_re))
    i = src.index('{', m.start())
    depth = 0
    for j in range(i, len(src)):
        if src[j] == '{':
            depth += 1
        elif src[j] == '}':
            depth -= 1
            if depth == 0:
                if not semicolon:
                    return src[m.start():j + 1]
                k = src.find(';', j)
                return src[m.start():k + 1]
    sys.exit("carve.py: unbalanced braces in %s" % what)


MEMBER_RE = re.compile(r'^\s*[A-Za-z_][A-Za-z0-9_ ]*?\**\s*(\*?)\s*'
                       r'([A-Za-z_][A-Za-z0-9_]*)\s*(\[[^\]]*\])?\s*;\s*$')


def struct_members(src, name):
    body = extract_block(src, r'struct\s+%s\s*\{' % re.escape(name), name)
    inner = body[body.index('{') + 1:body.rindex('}')]
    out = []
    for line in inner.splitlines():
        line = line.split('/*')[0].strip()
        if not line or line.startswith('//'):
            continue
        m = MEMBER_RE.match(line)
        if not m:
            sys.exit("carve.py: cannot parse member line in struct %s: %r"
                     % (name, line))
        out.append(m.group(2))
    if not out:
        sys.exit("carve.py: struct %s parsed to zero members" % name)
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--repo', required=True)
    ap.add_argument('--outdir', required=True)
    args = ap.parse_args()

    aci = read(os.path.join(args.repo, 'hw/xbox/mcpx/aci.c'))
    ac97 = read(os.path.join(args.repo, 'hw/audio/ac97_int.h'))

    pieces = [
        extract_block(aci, r'typedef struct MCPXACIState\s*\{',
                      'MCPXACIState'),
        extract_block(aci, r'static int mcpx_aci_post_load\s*\(',
                      'mcpx_aci_post_load', semicolon=False),
        extract_block(aci, r'static const VMStateDescription '
                           r'vmstate_mcpx_aci_bm_regs\s*=',
                      'vmstate_mcpx_aci_bm_regs'),
        extract_block(aci, r'static const VMStateDescription '
                           r'vmstate_mcpx_aci_ac97\s*=',
                      'vmstate_mcpx_aci_ac97'),
        extract_block(aci, r'static const VMStateDescription '
                           r'vmstate_mcpx_aci\s*=',
                      'vmstate_mcpx_aci'),
    ]

    os.makedirs(args.outdir, exist_ok=True)

    with open(os.path.join(args.outdir, 'carved.c'), 'w') as fh:
        fh.write('/* GENERATED by carve.py from hw/xbox/mcpx/aci.c. */\n')
        fh.write('#include "harness.h"\n\n')
        fh.write('\n\n'.join(pieces))
        fh.write('\n\nconst VMStateDescription *aci_vmsd = &vmstate_mcpx_aci;\n')
        fh.write('\n#include "body.c.inc"\n')

    link = struct_members(ac97, 'AC97LinkState')
    bm = struct_members(ac97, 'AC97BusMasterRegs')
    with open(os.path.join(args.outdir, 'members.c.inc'), 'w') as fh:
        fh.write('/* GENERATED by carve.py from hw/audio/ac97_int.h. */\n')
        fh.write('static const HarnessMember link_members[] = {\n')
        for n in link:
            fh.write('    { "%s", offsetof(AC97LinkState, %s),'
                     ' sizeof(((AC97LinkState *)0)->%s) },\n' % (n, n, n))
        fh.write('};\n\n')
        fh.write('static const HarnessMember bm_members[] = {\n')
        for n in bm:
            fh.write('    { "%s", offsetof(AC97BusMasterRegs, %s),'
                     ' sizeof(((AC97BusMasterRegs *)0)->%s) },\n' % (n, n, n))
        fh.write('};\n')

    print('carve.py: %d AC97LinkState members, %d AC97BusMasterRegs members'
          % (len(link), len(bm)))


if __name__ == '__main__':
    main()
