#!/usr/bin/env python3
"""Turn a pathfind run's steps.jsonl into a timed route (lane.fps20786).

    steps2route.py <steps.jsonl> --name NAME --gameplay N --loop TOKENS
                   [--hold-s 600] [--offset 4] [--state first-run]

Every step up to and including step N (the one pathfind read as gameplay)
plays its action at the step's own time + offset seconds after launch, with
pathfind's input mapping (pathfind.py send(): d-pad = the hat, a button is a
120-ms press, then 0.35 s, and 0.25 s after every token). Pathfind took each
step 8-15 s apart because it waited for a model, and every screen it passed
waits for input, so its pace is the safe one: a press can land late, not
early. After step N: `mark gameplay`, then the loop TOKENS (pathfind's genre
loop grammar) repeated to cover --hold-s, with a frame every ~30 s.
"""
import argparse, json

HAT = {"UP": ("HATY", "min"), "DOWN": ("HATY", "max"), "LEFT": ("HATX", "min"), "RIGHT": ("HATX", "max")}
STICK = {"up": [("LY", "min")], "down": [("LY", "max")], "left": [("LX", "min")], "right": [("LX", "max")],
         "upleft": [("LY", "min"), ("LX", "min")], "upright": [("LY", "min"), ("LX", "max")]}
RSTICK = {"up": [("RY", "min")], "down": [("RY", "max")], "left": [("RX", "min")], "right": [("RX", "max")]}


def tok_lines(tok):
    """(route lines, seconds) for one pathfind token."""
    if tok in HAT:
        ax, v = HAT[tok]
        return [f"axis {ax} {v}", f"axis {ax} mid", "wait 0.6"], 0.6
    if ":" not in tok:
        return [f"press {tok} 120", "wait 0.6"], 0.72
    parts = tok.split(":")
    s = float(parts[-1])
    if parts[0] in ("STICK", "RSTICK"):
        axes = (STICK if parts[0] == "STICK" else RSTICK)[parts[1]]
        return ([f"axis {a} {v}" for a, v in axes] + [f"wait {s}"] +
                [f"axis {a} mid" for a, _ in axes] + ["wait 0.25"]), s + 0.25
    if parts[0] in ("RT", "LT"):
        return [f"axis {parts[0]} max", f"wait {s}", f"axis {parts[0]} min", "wait 0.25"], s + 0.25
    if parts[0] == "HOLD":
        return [f"hold {parts[1]}", f"wait {s}", f"release {parts[1]}", "wait 0.25"], s + 0.25
    raise SystemExit(f"token not handled: {tok}")


ap = argparse.ArgumentParser()
ap.add_argument("steps")
ap.add_argument("--name", required=True)
ap.add_argument("--gameplay", type=int, required=True)
ap.add_argument("--loop", required=True, help="comma-separated pathfind tokens")
ap.add_argument("--hold-s", type=float, default=600)
ap.add_argument("--offset", type=float, default=4)
ap.add_argument("--state", default="first-run")
ap.add_argument("--source", default="")
a = ap.parse_args()

steps = [json.loads(l) for l in open(a.steps)]
out = [f"# state: {a.state}",
       f"# {a.name}: generated by docs/lanes/fps20786/steps2route.py from pathfind's",
       f"# recorded run {a.source or a.steps} (steps 1-{a.gameplay}, then a genre loop).",
       "# Each step's input plays at the step's own time + %.0f s; a frame per step." % a.offset]
clock = 0.0
for s in steps:
    if s["n"] > a.gameplay:
        break
    at = float(s["t"]) + a.offset
    if at > clock:
        out.append("wait %.1f" % (at - clock))
        clock = at
    out.append(f"shot s{s['n']:02d}-{s['state']}")
    out.append(f"# step {s['n']} [{s['state']}] {s.get('why', '')[:100]}")
    for tok in s.get("action", []):
        lines, secs = tok_lines(tok)
        out += lines
        clock += secs
out.append("wait 3")
out.append("mark gameplay")
clock += 3
body, per = [], 0.0
for tok in a.loop.split(","):
    lines, secs = tok_lines(tok)
    body += lines
    per += secs
inner = max(1, int(30 // per))
outer = int(a.hold_s // (inner * per)) + 1
out.append(f"# genre loop: {per:.1f} s, {inner} per frame, {outer} frames")
out.append(f"repeat {outer} {{")
out.append("shot hold")
out.append(f"repeat {inner} {{")
out += body
out.append("}")
out.append("}")
clock += outer * inner * per
out.append(f"# route ends ~{clock:.0f} s after launch")
print("\n".join(out))
