/* GENERATED by tools/nv2a_probe/gen_window.py -- do not edit.
 *
 * Source of truth: hw/xbox/nv2a/nv2a.c
 * Regenerate:      python3 tools/nv2a_probe/gen_window.py --write
 * Verify:          python3 tools/nv2a_probe/gen_window.py --check
 *
 * The NV2A MMIO BAR is 16 MiB. Everything outside it is refused by the
 * probe itself. Flash is mirrored at 0xff000000 and the SMC, SMBus and
 * EEPROM are I2C devices behind I/O ports -- none of them is MMIO, so an
 * MMIO-only probe cannot reach them even if this list were wrong.
 */
#ifndef NV2A_WINDOW_H
#define NV2A_WINDOW_H

#include <stdint.h>
#include <stdbool.h>

#define NV2A_MMIO_SIZE 0x01000000u

typedef struct { const char *name; uint32_t offset, size; bool writable; } nv2a_block_t;

static const nv2a_block_t kNv2aBlocks[] = {
    { "PMC",       0x000000u, 0x001000u, true },
    { "PBUS",      0x001000u, 0x001000u, true },
    { "PFIFO",     0x002000u, 0x002000u, true },
    { "PRMA",      0x007000u, 0x001000u, true },
    { "PVIDEO",    0x008000u, 0x001000u, true },
    { "PTIMER",    0x009000u, 0x001000u, true },
    { "PCOUNTER",  0x00a000u, 0x001000u, true },
    { "PVPE",      0x00b000u, 0x001000u, true },
    { "PTV",       0x00d000u, 0x001000u, true },
    { "PRMFB",     0x0a0000u, 0x020000u, true },
    { "PRMVIO",    0x0c0000u, 0x001000u, true },
    { "PFB",       0x100000u, 0x001000u, true },
    { "PSTRAPS",   0x101000u, 0x001000u, true },
    { "PGRAPH",    0x400000u, 0x002000u, true },
    { "PCRTC",     0x600000u, 0x001000u, true },
    { "PRMCIO",    0x601000u, 0x001000u, true },
    { "PRAMDAC",   0x680000u, 0x001000u, true },
    { "PRMDIO",    0x681000u, 0x001000u, true },
    { "USER",      0x800000u, 0x800000u, false },
};
#define NV2A_NUM_BLOCKS 19

/* write-excluded: USER -- FIFO DMA-push user area: a write here submits pushbuffer work, which phase one explicitly does not do. */

/* Reads may be wider than writes: any offset inside the BAR. */
static inline bool nv2a_offset_readable(uint32_t off)
{
    return off + 4u > off && off + 4u <= NV2A_MMIO_SIZE;
}

/* Registers a blind sweep must never write. Refused in the PROBE, not
 * only in the driver, because the host is the thing most likely to have
 * a bug in it. See gen_window.py for why each is here. */
typedef struct { uint32_t offset; const char *name; } nv2a_hazard_t;
static const nv2a_hazard_t kNv2aHazards[] = {
    { 0x000000u, "NV_PMC_BOOT_0" },
    { 0x000004u, "(measured)" },
    { 0x000200u, "NV_PMC_ENABLE" },
    { 0x003200u, "NV_PFIFO_CACHE1_PUSH0" },
    { 0x003204u, "NV_PFIFO_CACHE1_PUSH1" },
    { 0x003210u, "NV_PFIFO_CACHE1_PUT" },
    { 0x003214u, "NV_PFIFO_CACHE1_STATUS" },
    { 0x003220u, "NV_PFIFO_CACHE1_DMA_PUSH" },
    { 0x003224u, "NV_PFIFO_CACHE1_DMA_FETCH" },
    { 0x003228u, "NV_PFIFO_CACHE1_DMA_STATE" },
    { 0x00322cu, "NV_PFIFO_CACHE1_DMA_INSTANCE" },
    { 0x003240u, "NV_PFIFO_CACHE1_DMA_PUT" },
    { 0x003244u, "NV_PFIFO_CACHE1_DMA_GET" },
    { 0x003248u, "NV_PFIFO_CACHE1_REF" },
    { 0x00324cu, "NV_PFIFO_CACHE1_DMA_SUBROUTINE" },
    { 0x003250u, "NV_PFIFO_CACHE1_PULL0" },
    { 0x003254u, "NV_PFIFO_CACHE1_PULL1" },
    { 0x003270u, "NV_PFIFO_CACHE1_GET" },
    { 0x003280u, "NV_PFIFO_CACHE1_ENGINE" },
    { 0x0032a0u, "NV_PFIFO_CACHE1_DMA_DCOUNT" },
    { 0x0032a4u, "NV_PFIFO_CACHE1_DMA_GET_JMP_SHADOW" },
    { 0x0032a8u, "NV_PFIFO_CACHE1_DMA_RSVD_SHADOW" },
    { 0x0032acu, "NV_PFIFO_CACHE1_DMA_DATA_SHADOW" },
    { 0x003800u, "NV_PFIFO_CACHE1_METHOD" },
    { 0x003804u, "NV_PFIFO_CACHE1_DATA" },
    { 0x008700u, "NV_PVIDEO_BUFFER" },
    { 0x008704u, "NV_PVIDEO_STOP" },
    { 0x008900u, "NV_PVIDEO_BASE" },
    { 0x008908u, "NV_PVIDEO_LIMIT" },
    { 0x008920u, "NV_PVIDEO_OFFSET" },
    { 0x400fc4u, "NV_PGRAPH_CHEOPS_OFFSET" },
    { 0x600800u, "NV_PCRTC_START" },
    { 0x680500u, "NV_PRAMDAC_NVPLL_COEFF" },
    { 0x680504u, "NV_PRAMDAC_MPLL_COEFF" },
    { 0x680508u, "NV_PRAMDAC_VPLL_COEFF" },
    { 0x680514u, "NV_PRAMDAC_PLL_TEST_COUNTER" },
};
#define NV2A_NUM_HAZARDS 36

static inline const char *nv2a_hazard_name(uint32_t off)
{
    for (int i = 0; i < NV2A_NUM_HAZARDS; ++i)
        if (kNv2aHazards[i].offset == off) return kNv2aHazards[i].name;
    return 0;
}

/* Writes must land inside a modelled, write-enabled block. */
static inline bool nv2a_offset_writable(uint32_t off)
{
    if (off & 3u) return false;              /* unaligned */
    if (off + 4u <= off) return false;       /* wrap */
    for (int i = 0; i < NV2A_NUM_BLOCKS; ++i) {
        const nv2a_block_t *b = &kNv2aBlocks[i];
        if (!b->writable) continue;
        if (off >= b->offset && off + 4u <= (uint32_t)(b->offset + b->size))
            return true;
    }
    return false;
}

/* The check the probe actually applies to a write. */
static inline bool nv2a_offset_write_allowed(uint32_t off)
{
    return nv2a_offset_writable(off) && nv2a_hazard_name(off) == 0;
}

#endif /* NV2A_WINDOW_H */
