#!/usr/bin/env python3
"""Per-title table for #782: which Thor-made goldens sign with the HDD key.

Reads the dispatch titlestate store (golden.json, saves/<tid>/<golden>/save.json,
the .sig files inside each golden) and the title names from the compat CSV.
Writes TABLE.md next to this file. The answer is offline evidence only: a title
is "no" only where a frame-confirmed Nova load is on record, "yes (likely)" where
the golden carries a .sig file, and "unknown" otherwise.
"""
import csv
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
D = os.path.join(os.environ["DISPATCH_DIR"], "titlestate")
CSV = "/home/justin/hakux-work/titles/xemu-compat-2026-09-25.csv"

NO = {
    "4B4E002D": "frame-confirmed: lane.local returning run 1-1791056447-lanelocal-2267406 reached play on the Nova (pathfind NOTES, 10-03)",
    "53450029": "frame-confirmed: pathfind runs/spikeout-hold, returning on the Thor-made golden, PASS on the Nova (pathfind NOTES)",
}

names = {}
with open(CSV, encoding="utf-8", errors="replace") as fh:
    for r in csv.DictReader(fh):
        names.setdefault(r["canonical_title_id"].upper(), r["name"])

goldens = json.load(open(os.path.join(D, "golden.json")))["titles"]
rows = []
counts = {"yes (likely)": 0, "no": 0, "unknown": 0}
for tid in sorted(goldens):
    sv = (goldens[tid].get("golden") or {}).get("save")
    if not sv:
        continue
    base = os.path.join(D, "saves", tid, sv)
    src = json.load(open(os.path.join(base, "save.json")))["source"]["image"]
    if os.path.basename(src).split("-")[0] != "thor":
        continue
    sigs = sorted({f for _, _, fs in os.walk(base) for f in fs if f.endswith(".sig")})
    if tid in NO:
        ans, ev = "no", NO[tid]
    elif sigs:
        ans = "yes (likely)"
        ev = ("signature files " + ", ".join(sigs) + "; same kind as Forza's CarIcons.sig, "
              "whose Thor golden reads damaged on the Nova. Not frame-tested for this title")
    else:
        ans, ev = "unknown", "no .sig in the golden; not frame-tested on the Nova"
    counts[ans] += 1
    rows.append("| %s | %s | %s | %s | %s |" % (names.get(tid, "?"), tid, sv, ans, ev))

out = [
    "# #782: the Thor-made goldens on the Nova",
    "",
    "Generated by `make_table.py` from `dispatch/titlestate/golden.json`, each golden's",
    "`save.json` (source image) and its `.sig` files. Forza (`4D53006E`) is not in the table:",
    "its golden was re-harvested on the Nova (`5725499d3c7f`, source `nova-held.qcow2`).",
    "",
    "| title | title id | golden | signs with HDD key | evidence |",
    "|---|---|---|---|---|",
] + rows + [
    "",
    "Thor-made goldens still open: %d. Counts: %s." % (len(rows), ", ".join(
        "%s %d" % (k, v) for k, v in counts.items())),
    "",
]
with open(os.path.join(HERE, "TABLE.md"), "w", encoding="utf-8") as fh:
    fh.write("\n".join(out))
print(len(rows), counts)
