"""Zero-shot text prompts per screen state (pathclass tier 2's starting point, before any trained head)."""

STATES = ["intro_video", "publisher_logo", "title_screen", "main_menu", "submenu", "profile_creation",
          "name_entry", "save_load_prompt", "controller_prompt", "loading", "cutscene", "pause", "gameplay",
          "results", "game_over", "black", "unknown"]

PROMPTS = {
    "intro_video": ["a cinematic intro video of a video game", "a pre-rendered opening movie of a video game",
                    "an attract mode demo of a video game with a logo overlay"],
    "publisher_logo": ["a video game publisher logo on a plain background", "a game studio logo splash screen",
                       "a legal copyright and warning text screen", "a company logo on a black screen"],
    "title_screen": ["a video game title screen with the game logo and press start",
                     "the title logo of a video game with the text PRESS START"],
    "main_menu": ["a video game main menu with options like new game, continue, options",
                  "a main menu list of a video game"],
    "submenu": ["a video game menu to select a mode, level, character or car",
                "a video game selection screen with a grid of options", "a video game options settings menu"],
    "profile_creation": ["a video game screen to create or select a player profile",
                         "a video game save slot selection screen"],
    "name_entry": ["an on-screen keyboard to enter a name in a video game",
                   "a video game name entry screen with letters to pick"],
    "save_load_prompt": ["a video game dialog box asking to save or load, yes or no",
                         "a video game message about memory unit storage and saved data"],
    "controller_prompt": ["a video game screen saying press start to begin or connect a controller",
                          "a video game screen showing the controller button layout"],
    "loading": ["a video game loading screen with a progress bar", "a video game screen with the word loading",
                "a video game loading screen with a hint text"],
    "cutscene": ["a story cutscene in a video game with letterbox black bars",
                 "a video game cutscene with subtitles and characters talking"],
    "pause": ["a video game paused with a pause menu over the game", "the word PAUSED over a video game scene"],
    "gameplay": ["video game gameplay with a heads-up display", "a player controlling a character in a video game",
                 "a racing game being played with speedometer and lap counter",
                 "a first person shooter being played with a crosshair and ammo counter",
                 "a fighting game match with health bars"],
    "results": ["a video game results screen with scores and rankings", "a race results table in a video game",
                "a video game showing WINNER or PERFECT after a round"],
    "game_over": ["a video game game over screen", "a video game mission failed retry screen"],
    "black": ["a completely black screen", "a black image"],
    "unknown": ["an android phone home screen", "corrupted garbage graphics", "a smartphone app launcher"],
}
